"""
struct_core: A common engineering schema for 2D/3D structural analysis, structural dynamics,
code design, and reinforcement detailing.
"""

from . import analysis_result, design_result, detailing_result, structural_model
from .analysis_result import (
    AnalysisResult,
    BeamSectionForce,
    ElementForceResult,
    ElementResult,
    ModalResult,
    ModeShape,
    NodeDisplacement,
    NodeReaction,
    NodeResult,
    TimeHistoryResult,
    TimeStepResult,
)
from .base import (
    AnalysisCaseId,
    BaseSchemaModel,
    ElementId,
    IDType,
    LoadCaseId,
    MaterialId,
    NodeId,
    SectionId,
)
from .design_result import (
    CodeCheckResult,
    DesignResult,
    ElementDesignResult,
    FlexureDesignResult,
    MaterialDesignResult,
    ShearDesignResult,
)
from .detailing_result import (
    Anchorage,
    Bar,
    BarLayout,
    BarSchedule,
    BarScheduleItem,
    DetailingResult,
    ElementDetailingResult,
    HookGeometry,
    LapSplice,
    RebarLayer,
    StirrupLayout,
)
from .metadata import Metadata, ModelMetadata, Units, UnitsSchema
from .project import Project
from .serialization import from_dict, from_json, load_json, save_json, to_dict, to_json
from .structural_model import (
    AnalysisCase,
    AnalysisCaseSchema,
    BaseAnalysisCase,
    BaseAnalysisCaseSchema,
    BaseElement,
    BaseElementSchema,
    BaseMaterial,
    BaseMaterialSchema,
    BaseSection,
    BaseSectionSchema,
    BeamElement,
    BeamElementSchema,
    BilinearMaterial,
    BilinearMaterialSchema,
    CircularSection,
    CircularSectionSchema,
    DistributedLoad,
    DistributedLoadSchema,
    ElasticMaterial,
    ElasticMaterialSchema,
    Element,
    ElementSchema,
    GeneralSection,
    GeneralSectionSchema,
    GroundMotion,
    GroundMotionSchema,
    LinearStaticAnalysis,
    LinearStaticAnalysisSchema,
    LoadCase,
    LoadCaseFactor,
    LoadCaseFactorSchema,
    LoadCaseSchema,
    LoadCombination,
    LoadCombinationSchema,
    Material,
    MaterialSchema,
    ModalAnalysis,
    ModalAnalysisSchema,
    Node,
    NodeSchema,
    NonlinearStaticAnalysis,
    NonlinearStaticAnalysisSchema,
    PointLoad,
    PointLoadSchema,
    RectangularSection,
    RectangularSectionSchema,
    Section,
    SectionSchema,
    SpringElement,
    SpringElementSchema,
    StructuralModel,
    StructuralValidationError,
    Support,
    SupportSchema,
    TimeHistoryAnalysis,
    TimeHistoryAnalysisSchema,
    TrussElement,
    TrussElementSchema,
    validate_structural_model,
)
from .structural_model.registry import ElementRegistry

# Plural aliases matching ecosystem naming conventions
analysis_results = analysis_result
design_results = design_result
detailing_results = detailing_result

__version__ = "0.2.0"

__all__ = [
    # Subpackages
    "structural_model",
    "analysis_result",
    "design_result",
    "detailing_result",
    "analysis_results",
    "design_results",
    "detailing_results",
    # Metadata & Units
    "Metadata",
    "Units",
    "ModelMetadata",
    "UnitsSchema",
    # Base / IDs
    "BaseSchemaModel",
    "IDType",
    "NodeId",
    "ElementId",
    "MaterialId",
    "SectionId",
    "LoadCaseId",
    "AnalysisCaseId",
    # Structural Model Entities
    "Node",
    "NodeSchema",
    "BaseElement",
    "BaseElementSchema",
    "TrussElement",
    "TrussElementSchema",
    "BeamElement",
    "BeamElementSchema",
    "SpringElement",
    "SpringElementSchema",
    "Element",
    "ElementSchema",
    "ElementRegistry",
    "BaseMaterial",
    "BaseMaterialSchema",
    "ElasticMaterial",
    "ElasticMaterialSchema",
    "BilinearMaterial",
    "BilinearMaterialSchema",
    "Material",
    "MaterialSchema",
    "BaseSection",
    "BaseSectionSchema",
    "RectangularSection",
    "RectangularSectionSchema",
    "CircularSection",
    "CircularSectionSchema",
    "GeneralSection",
    "GeneralSectionSchema",
    "Section",
    "SectionSchema",
    "Support",
    "SupportSchema",
    "PointLoad",
    "PointLoadSchema",
    "DistributedLoad",
    "DistributedLoadSchema",
    "GroundMotion",
    "GroundMotionSchema",
    "LoadCase",
    "LoadCaseSchema",
    "LoadCaseFactor",
    "LoadCaseFactorSchema",
    "LoadCombination",
    "LoadCombinationSchema",
    "BaseAnalysisCase",
    "BaseAnalysisCaseSchema",
    "LinearStaticAnalysis",
    "LinearStaticAnalysisSchema",
    "NonlinearStaticAnalysis",
    "NonlinearStaticAnalysisSchema",
    "ModalAnalysis",
    "ModalAnalysisSchema",
    "TimeHistoryAnalysis",
    "TimeHistoryAnalysisSchema",
    "AnalysisCase",
    "AnalysisCaseSchema",
    "StructuralModel",
    "validate_structural_model",
    "StructuralValidationError",
    # Analysis Results
    "NodeDisplacement",
    "NodeReaction",
    "NodeResult",
    "BeamSectionForce",
    "ElementForceResult",
    "ElementResult",
    "ModeShape",
    "ModalResult",
    "TimeStepResult",
    "TimeHistoryResult",
    "AnalysisResult",
    # Design Results
    "CodeCheckResult",
    "FlexureDesignResult",
    "ShearDesignResult",
    "MaterialDesignResult",
    "ElementDesignResult",
    "DesignResult",
    # Detailing Results
    "Bar",
    "RebarLayer",
    "StirrupLayout",
    "BarLayout",
    "HookGeometry",
    "LapSplice",
    "Anchorage",
    "BarScheduleItem",
    "BarSchedule",
    "ElementDetailingResult",
    "DetailingResult",
    # Project & Utilities
    "Project",
    "to_dict",
    "from_dict",
    "to_json",
    "from_json",
    "save_json",
    "load_json",
]
